# Generated by Django 4.2.1 on 2024-03-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0012_mother_is_mother'),
        ('teacher', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mother.child'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
