# Generated by Django 4.2.1 on 2024-03-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_report_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created',
        ),
    ]
