# Generated by Django 4.2.7 on 2024-05-03 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_alter_report_id_alter_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.AddField(
            model_name='report',
            name='activities',
            field=models.CharField(blank=True, choices=[('drawing and coloring', 'drawing and coloring'), ('music', 'music'), ('reading stories', 'reading stories')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='attiude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='report',
            name='learn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='mood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
