# Generated by Django 4.2.7 on 2024-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_remove_report_text_report_activities_report_attiude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='child_location',
            field=models.CharField(blank=True, choices=[('arrive', 'arrive'), ('left', 'left')], max_length=200, null=True),
        ),
    ]
