# Generated by Django 4.2.7 on 2024-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_report_child_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='child_location',
        ),
        migrations.AddField(
            model_name='teacher',
            name='child_location',
            field=models.CharField(blank=True, choices=[('arrive', 'arrive'), ('left', 'left')], max_length=200, null=True),
        ),
    ]
