# Generated by Django 4.2.7 on 2024-05-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_remove_teacher_child_location_report_child_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='child_location',
            new_name='location',
        ),
    ]
