# Generated by Django 4.2.7 on 2024-05-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_report_important_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
