# Generated by Django 4.2.1 on 2024-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0002_rename_full_name_mother_name_child_age_child_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
