# Generated by Django 4.2.1 on 2024-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0003_child_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='username',
        ),
        migrations.AddField(
            model_name='mother',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
