# Generated by Django 4.2.1 on 2024-03-22 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0004_remove_child_username_mother_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('name', models.CharField(blank=True, choices=[('meat', 'Meat'), ('milk', 'milk')], max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mother.child')),
            ],
        ),
    ]
