# Generated by Django 4.2.1 on 2024-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0005_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='meal',
            field=models.CharField(blank=True, choices=[('meat', 'Meat'), ('milk', 'milk')], max_length=200, null=True, unique_for_date=True),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
