# Generated by Django 4.2.1 on 2024-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0006_child_meal_delete_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mother',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='meal',
            field=models.CharField(blank=True, choices=[('meat', 'Meat'), ('milk', 'milk')], max_length=200, null=True),
        ),
    ]
