# Generated by Django 4.2.1 on 2024-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0007_child_featured_image_mother_address_mother_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='staticfiles/images/'),
        ),
    ]
