# Generated by Django 4.2.1 on 2024-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0008_alter_child_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
    ]
