# Generated by Django 4.2.1 on 2024-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0009_child_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='is_mother',
            field=models.BooleanField(default=False),
        ),
    ]
