# Generated by Django 4.2.1 on 2024-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0011_remove_mother_is_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='is_mother',
            field=models.BooleanField(default=False),
        ),
    ]
