# Generated by Django 4.2.1 on 2024-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0013_remove_mother_is_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
