# Generated by Django 4.2.1 on 2024-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0014_child_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
