# Generated by Django 4.2.1 on 2024-04-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0016_alter_child_id_alter_mother_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mother',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
