# Generated by Django 4.2.7 on 2024-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0020_alter_child_id_alter_mother_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='state_health',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.CharField(blank=True, choices=[('5', '5'), ('6', '6')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='meal',
            field=models.CharField(blank=True, choices=[('meat', 'Meat'), ('milk', 'milk'), ('sandwich', 'sandwich'), ('Nuggets', 'Nuggets'), ('Burger', 'Burger'), ('Pasta', 'Pasta'), ('Pie', 'Pie'), ('Pizza', 'Pizza'), ('Pancake', 'Pancake'), ('Waffle', 'Waffle')], max_length=200, null=True),
        ),
    ]
