# Generated by Django 4.2.7 on 2024-05-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_delete_report'),
        ('mother', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
