# Generated by Django 4.2.7 on 2024-05-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_delete_report'),
        ('mother', '0023_child_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher'),
        ),
    ]
