# Generated by Django 4.2.7 on 2024-06-03 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0024_alter_child_teach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Important_notice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='child',
            name='Important_notice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.CharField(blank=True, choices=[('arrive', 'arrive'), ('left', 'left')], max_length=200, null=True),
        ),
    ]
