# Generated by Django 4.2.7 on 2024-06-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_delete_report'),
        ('mother', '0025_remove_report_important_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
