# Generated by Django 4.2.7 on 2024-06-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0026_alter_child_teach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='Important_notice',
            new_name='Important_nots',
        ),
    ]
