# Generated by Django 4.2.7 on 2024-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0028_mother_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/'),
        ),
    ]
