# Generated by Django 4.2.7 on 2024-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0030_child_meal_images_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='meal_images_path',
            field=models.CharField(blank=True, choices=[('meat', 'images/meat.jpg'), ('milk', 'images/milk.jpg'), ('sandwich', 'images/sandwich.jpg'), ('nuggets', 'images/Nuggets.jpg'), ('burger', 'images/Burger.jpg'), ('pasta', 'images/Pasta.jpg'), ('pie', 'images/Pie.jpg'), ('pizza', 'images/Pizza.jpg'), ('pancake', 'images/Pancake.jpg'), ('waffle', 'images/Waffle.jpg')], max_length=200, null=True),
        ),
    ]
