# Generated by Django 4.2.7 on 2024-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0032_alter_child_meal_alter_child_meal_images_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='staticfiles/images/'),
        ),
    ]
