# Generated by Django 4.2.7 on 2024-06-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0033_alter_child_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='Important_nots',
            new_name='Important_notes',
        ),
    ]
